### ISSUE TITLE
Confusing information's structure in /projects.html

### ISSUE THREAD

**Issue by henriquecrang** [ecanali/ecanali.github.io#1]
I felt confused navigating through the Projects page.

Each project has a box, with it's title down low, in the same font size as the external bottom to GitHub. It took me a while to understand that that was the project's title.

Maybe it would be easier if the title was shown above the image, while the link to GitHub could be centered bellow it.

**Comment by ecanali** [comment]
Well noted, thank you for the advise! 

I've changed the layout highlighting the project's title and centering it with the GitHub link.
